package org.cytosm.pathfinder.exceptions;

/***
 * Abstract superclass of all exception generated by the routematcher.
 *
 *
 */
@SuppressWarnings("serial")
public class PathFinderException extends Exception {

    /***
     * Exception caused by route matcher module.
     * @param message additional info
     */
    public PathFinderException(final String message) {
        super(message);
    }

    /***
     *  Exception caused by route matcher module.
     * @param message additional info
     * @param cause original exception
     */
    public PathFinderException(final String message, final Throwable cause) {
        super(message, cause);
    }

    /***
     * Exception caused by route matcher module.
     *
     * @param cause original exception
     */
    public PathFinderException(final Throwable cause) {
        super(cause);
    }
}
