package org.cytosm.cypher2sql.lowering.sqltree;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * A select that has been generated by a SingleQuery from cypher.
 *
 * ScopeSelect represents a scope in the sense that
 * {@link org.cytosm.cypher2sql.lowering.sqltree.from.FromItem}s
 * of any child Select can only refer to other {@link WithSelect}s
 * living in the same {@link ScopeSelect}.
 *
 */
public class ScopeSelect extends SimpleOrScopeSelect {

    /**
     * Contains the list of queries that
     * will be rendered within a SQL WITH.
     * They can refer to each other
     */
    public List<WithSelect> withQueries = new ArrayList<>();

    /**
     * The return end up here.
     */
    public SimpleSelect ret;

    @Override
    public String toSQLString() {
        return "WITH " + withQueries.stream()
                .map(SQLNode::toSQLString)
                .collect(Collectors.joining(", ")) + "\n" +
                ret.toSQLString();
    }
}
